export const portfolioItems = {
	items: [
		{
			id: 1,
			title: 'Next.js Notion Clone',
			img: './note-keeper-img.png',
			desc: 'A sophisticated Notion-like application that allows users to create, edit, delete, import images, and publish a single pages accessible to anyone.',
			url: 'https://note-keeper-next13-app.vercel.app/',
			techStack: [
				'Nextjs',
				'Reactjs',
				'TypeScript',
				'TailwindCSS',
				'ShadcnUI',

				'PostgreSQL',
				'Convex',
				'Clerk',
				'Json Web Token',

				'Zustand',
				'Sonner',
				'Lucide React Icons',
			],
		},
		{
			id: 2,
			title: 'City Cemetery with Nextjs, Prisma and MySQL',
			img: './cemetery-img.png',
			desc: 'A web application for San Pablo City focused on recording and managing burial records in the city cemetery.',
			url: 'https://cemetery.sanpablocity.gov.ph/',
			techStack: [
				'Nextjs',
				'Reactjs',
				'TypeScript',
				'TailwindCSS',
				'ShadcnUI',

				'MySQL',
				'Prisma',
				'Axios',
				'MongoDB',
				'Expressjs',
				'Json Web Token',
				'Bcryptjs',

				'Zustand',
				'Sonner',
				'React-PDF',
			],
		},
		{
			id: 3,
			title: 'To Do List App with Next14, Prisma and PostgreSQL',
			img: './todolist-img.png',
			desc: 'A simple to-do list application focused on learning Prisma with PostgreSQL.',
			url: 'https://todolist-prisma-next14-app.vercel.app/',
			techStack: [
				'Nextjs',
				'Reactjs',
				'PostgreSQL',
				'TailwindCSS',
				'ShadcnUI',

				'Zustand',
				'Sonner',
				'Lucide React Icons',
			],
		},
		{
			id: 4,
			title: 'Static Nike Clone',
			img: './nike-clone-img.png',
			desc: 'A static Nike clone web application focused on learning Tailwind CSS and mobile responsiveness.',
			url: 'https://nike-clone-chi-ten.vercel.app/',
			techStack: ['Reactjs', 'TailwindCSS'],
		},
		{
			id: 5,
			title: 'Course Todolist App with Reactjs and Zustand',
			img: './course-todolist-img.png',
			desc: 'A static web application that allows users to create a simple course list. Zustand is used for state management.',
			url: 'https://react-zustand-mu.vercel.app/',
			techStack: ['Reactjs', 'Zustand'],
		},
	],
};
